name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  update-readme:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app-debug
          path: app/build/outputs/apk/debug

      - name: Generate APK download link
        run: echo "Download APK [here](https://github.com/${{ github.repository }}/releases/download/latest/my-app-debug)" > apk-link.txt

