name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  update-readme:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: my-app-debug
          path: app/build/outputs/apk/debug

      - name: Generate APK download link
        run: echo "Download APK [here](https://github.com/panchalamitr/Android-Notification-Reader/releases/download/latest/app-debug.apk)" > apk-link.txt

      - name: Update ReadMe
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const contents = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'apk-link.txt'), 'utf8').trim();
            const readmePath = path.join(process.env.GITHUB_WORKSPACE, 'README.md');
            let readme = fs.readFileSync(readmePath, 'utf8');
            const insertIndex = readme.indexOf('## ');
            const updatedReadme = readme.substring(0, insertIndex) + '\n\n' + contents + '\n\n' + readme.substring(insertIndex);
            fs.writeFileSync(readmePath, updatedReadme);
          token: ${{ secrets.GITHUB_TOKEN }}
